openapi: 3.0.0

info:
  title: 籃球情報室 Web API 文件
  version: 0.0.0
  description: Basketball Competition Dashboard Web API

externalDocs:
  description: Home Page
  url: https://github.com/Basketball-Competition-Dashboard

servers:
  - url: '{ORIGIN}/api/web'
    description: Web API service root
    variables:
      ORIGIN:
        default: http://127.0.0.1:5000
        description: The origin of the service

tags:
  - name: 測試
    description: Testing
  - name: 認證
    description: Authentication
  - name: 比賽
    description: Games
  - name: 球隊
    description: Teams
  - name: 球員
    description: Players

paths:
  /ping:
    get:
      tags:
        - 測試
      summary: 測試
      description: Ping Pong!
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                enum:
                  - Pong!
                example: 'Pong!'

  /auth/login:
    post:
      tags:
        - 認證
      summary: 登入
      description: Login
      requestBody:
        description: The request body for authentication
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
            examples:
              'Demo Jack':
                value:
                  name: 'Demo Manager Jack'
                  credential: 'Pa55w0rd'
              'Demo Zoe':
                value:
                  name: 'Demo Manager Zoe'
                  credential: 'A super safe password!'
      responses:
        '201':
          description: Logged in
          headers:
            Set-Cookie:
              schema:
                type: string
                example: >-
                  session_id=MTRlNGIzYzI0MTk3NGIzYjg3ODI2MjlhNWY1ZWRhNmE=;
                  HttpOnly; Max-Age=31536000; Path=/; SameSite=Strict
        '404':
          $ref: '#/components/responses/NotFoundError'
  
  /auth/logout:
    post:
      tags:
        - 認證
      summary: 登出
      description: Logout
      security:
        - SessionID: []
      responses:
        '204':
          description: Logged out
          headers:
            Set-Cookie:
              schema:
                type: string
                example: 'session_id=; HttpOnly; Max-Age=0; Path=/; SameSite=Strict'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /games:
    post:
      tags:
        - 比賽
      summary: 取得比賽資料
      description: Get games
      requestBody:
        $ref: '#/components/requestBodies/Pagination'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - page
                  - values
                properties:
                  page:
                    $ref: '#/components/schemas/PageMeta'
                  values:
                    $ref: '#/components/schemas/Games'
        '400':
          $ref: '#/components/responses/BadRequestError'

  /teams:
    post:
      tags:
        - 球隊
      summary: 取得球隊資料
      description: Get teams
      requestBody:
        $ref: '#/components/requestBodies/Pagination'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - page
                  - values
                properties:
                  page:
                    $ref: '#/components/schemas/PageMeta'
                  values:
                    $ref: '#/components/schemas/Teams'
        '400':
          $ref: '#/components/responses/BadRequestError'

  /players/profiles:
    post:
      tags:
        - 球員
      summary: 取得球員資料 - 介紹
      description: Get the profiles of players
      requestBody:
        $ref: '#/components/requestBodies/Pagination'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - page
                  - values
                properties:
                  page:
                    $ref: '#/components/schemas/PageMeta'
                  values:
                    $ref: '#/components/schemas/PlayerProfiles'
        '400':
          $ref: '#/components/responses/BadRequestError'

  /players/stats:
    post:
      tags:
        - 球員
      summary: 取得球員資料 - 表現數據
      description: Get the statistics of players
      requestBody:
        $ref: '#/components/requestBodies/Pagination'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - page
                  - values
                properties:
                  page:
                    $ref: '#/components/schemas/PageMeta'
                  values:
                    $ref: '#/components/schemas/PlayerStats'
        '400':
          $ref: '#/components/responses/BadRequestError'

components:
  schemas:
    Auth:
      description: Authentication data
      type: object
      required:
        - name
        - credential
      properties:
        name:
          type: string
          example: 'Manager Zoe'
        credential:
          type: string
          format: password
          example: 'A super safe password!'

    Game:
      description: Game data
      type: object
      required:
        - date
        - home_name
        - away_name
      properties:
        id:
          description: Game ID
          type: integer
          format: uint32
          example: 3001
        date:
          description: Date of the game
          type: string
          format: date
          example: '2024-05-06'
        home_name:
          description: Home team name
          type: string
          example: 'Celtics'
        away_name:
          description: Away team name
          type: string
          example: 'NETS'
        home_score:
          description: Home team score
          type: integer
          format: uint32
          example: 123
        away_score:
          description: Away team score
          type: integer
          format: uint32
          example: 98
        winner_name:
          description: Winner team name
          type: string
          example: 'Celtics'

    Games:
      description: Game data set
      type: array
      items:
        $ref: '#/components/schemas/Game'

    Team:
      description: Team data
      type: object
      required:
        - abbr
        - name
        - city
      properties:
        id:
          description: Team ID
          type: integer
          format: uint32
          example: 60020
        abbr:
          description: Team abbreviation
          type: string
          example: 'BOS'
        name:
          description: Team name
          type: string
          example: 'Celtics'
        city:
          description: Team city
          type: string
          example: 'Boston'
        coach:
          description: Team coach name
          type: string
          example: 'Joseph Mazzulla'
        year_founded:
          description: Team founded year
          type: integer
          format: int32
          example: 1946

    Teams:
      description: Team data set
      type: array
      items:
        $ref: '#/components/schemas/Team'

    PlayerProfile:
      description: Player profile data
      type: object
      required:
        - name
      properties:
        id:
          description: Player ID
          type: integer
          format: uint32
          example: 3695
        name:
          description: Player name
          type: string
          example: 'Precious Achiuwa'
        team_name:
          description: Team name
          type: string
          example: 'Knicks'
        position:
          description: Player position
          type: string
          example: 'F'
        birthdate:
          description: Player birthdate
          type: string
          format: date
          example: '1970-05-25'
        height:
          description: Player height
          type: string
          example: '6-8'
        weight:
          description: Player weight
          type: integer
          format: uint32
          example: 243
        country:
          description: Player country
          type: string
          example: 'Nigeria'

    PlayerProfiles:
      description: Player profile data set
      type: array
      items:
        $ref: '#/components/schemas/PlayerProfile'

    PlayerStat:
      description: Player statistics data
      type: object
      required:
        - name
        - game_name
      properties:
        id:
          description: Player ID
          type: integer
          format: uint32
          example: 3695
        name:
          description: Player name
          type: string
          example: 'Precious Achiuwa'
        game_name:
          description: >-
            Game name in the format of
            '{Game date} {Home team abbreviation} {Away team abbreviation}'
          type: string
          format: '[0-9]{4}-[0-9]{2}-[0-9]{2} [A-Z]{3} [A-Z]{3}'
          example: '240506 HOU MEM'
        assist:
          description: Player assist count
          type: integer
          format: uint32
          example: 20
        hit:
          description: Player hit count
          type: integer
          format: uint32
          example: 5
        steal:
          description: Player steal count
          type: integer
          format: uint32
          example: 6
        rebound:
          description: Player rebound count
          type: integer
          format: uint32
          example: 25
        free_throw:
          description: Player free throw count
          type: integer
          format: uint32
          example: 3
        score:
          description: Player score count
          type: integer
          format: uint32
          example: 24

    PlayerStats:
      description: Player statistics data set
      type: array
      items:
        $ref: '#/components/schemas/PlayerStat'

    PageMeta:
      description: Pagination metadata
      type: object
      required:
        - offset
        - length
      properties:
        offset:
          description: The offset of paginated data
          type: integer
          format: uint32
          example: 0
        length:
          description: The length of paginated data
          type: integer
          format: uint32
          example: 10

    SortMeta:
      description: Sorting metadata
      type: object
      required:
        - field
        - order
      properties:
        field:
          description: Field to sort by
          type: string
          example: 'name'
        order:
          description: Sort order
          type: string
          enum:
            - 'ascending'
            - 'descending'
          example: 'descending'

  requestBodies:
    Pagination:
      description: The request body for paginated data
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              page:
                $ref: '#/components/schemas/PageMeta'
              sort:
                $ref: '#/components/schemas/SortMeta'
          examples:
            'order by name asc':
              value:
                page:
                  offset: 0
                  length: 10
                sort:
                  field: 'name'
                  order: 'ascending'
            'order by date desc':
              value:
                page:
                  offset: 0
                  length: 20
                sort:
                  field: 'date'
                  order: 'descending'
            'default':
              value: {}

  responses:
    BadRequestError:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Your request is invalid.'

    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'You are not authorized to access this resource.'

    NotFoundError:
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'The resource you are accessing is not found.'

  securitySchemes:
    SessionID:
      type: apiKey
      description: The cookie for authentication
      in: cookie
      name: session_id
